### ISSUE TITLE
Log sent emails

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-mail#15]
Log in a log file somewhere 
all emails **SENT** successfully 

json or txt format 

Subject || TO || From || Date 

( to be able to add more informations in the log line ) 

and write some explanations in the readme.md file

**Comment by bidi47** [comment]
upgrading from 3.1 to 3.2.1 returns this error

Laminas\ServiceManager\Exception\ServiceNotFoundException raised in file
D:\Programs\XAMPP\htdocs\tryk\api\vendor\laminas\laminas-servicemanager\src\ServiceManager.php line 557:
Message: Unable to resolve service "Dot\Mail\Service\LogServiceInterface" to a factory; are you certain you provided it
during configuration?

**Comment by bidi47** [comment]
fixed with adding this line in _config/config.php_
`Dot\Mail\ConfigProvider::class,`

also make sure to clear the cache
