### ISSUE TITLE
ability to save an email in a certain folder 

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-mail#23]
Purpose : when sending emails using IMAP Transport, we want to be able to save a copy of the sent email in , let's say , Sent folder 
** value need to come from local.php

This is how is done is Roudncube 
https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_imap.php#L2558

Documentation in laminas-mail 
https://docs.laminas.dev/laminas-mail/read/

**Comment by bidi47** [comment]
added new releases for v3 and v4 with feature to save an outgoing email in a folder
