### ISSUE TITLE
Function createStorage should not be used at the beginning

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-mail#35]
https://github.com/dotkernel/dot-mail/blob/3.0/src/Factory/MailServiceAbstractFactory.php#L195

the function createStorage need to verify each param if is not null , and thourw an excception if something 

2. the function should not be called at each request 
https://github.com/dotkernel/frontend/issues/284

**Comment by bidi47** [comment]
updated in https://github.com/dotkernel/dot-mail/releases/tag/3.4.3
once verified, i'll make the update on the dot-mail v4 branch too

**Comment by bidi47** [comment]
v3 checks out
updated v4 https://github.com/dotkernel/dot-mail/pull/41

**Comment by bidi47** [comment]
v4 is tested too
