### ISSUE TITLE
Template renderer in dot-mail?

### ISSUE THREAD

**Issue by mstyle21** [dotkernel/dot-mail#6]
Why is used template rederer in dot mail?
Maybe it's an idea to remove it or changed so it is not used in console.

**Comment by gabidj** [comment]
Hello @mstyle21 
The mail package shouldn't require a template renderer

Package will be splitted, see issue #7

**Comment by gabidj** [comment]
Last commit with template: (as required in the frontend package)
Right before: e833117b1cdcf13084fa1920add7d966d68536e6

There will be a version cleanup.
